version: "3.9"
   
services:
  web:
      build: .
      command: python manage.py runserver 0.0.0.0:8000
      volumes:
        - .:/backend
      ports:
        - "8000:8000"
      depends_on:
        - db

  db:
    restart: always
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRESS_PORT=5432
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - db
    ports:
      - "5051:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: root
    restart: always

volumes:
  postgres_data:
