# Generated by Django 4.1.2 on 2022-10-12 18:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_status_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='delete_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 12, 20, 47, 25, 361530), null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 12, 20, 47, 25, 361530), null=True),
        ),
    ]
