# Generated by Django 4.1.2 on 2022-10-16 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_category_name_alter_company_delete_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='delete_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
