# Generated by Django 4.1.2 on 2022-10-16 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_company_category_company_industry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='category',
        ),
        migrations.RemoveField(
            model_name='company',
            name='industry',
        ),
    ]
