name: Build Szakal and deploy to prod on AWS
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Clone the repository
        uses: actions/checkout@v2

      - name: Set up environment variables
        run: |
          echo "DB_NAME=${{ secrets.DB_NAME_PROD }}" >> $GITHUB_ENV
          echo "DB_USER=${{ secrets.DB_USER_PROD }}" >> $GITHUB_ENV
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD_PROD }}" >> $GITHUB_ENV
          echo "DB_HOST=${{ secrets.DB_HOST_PROD }}" >> $GITHUB_ENV
          echo "DB_PORT=${{ secrets.DB_PORT_PROD }}" >> $GITHUB_ENV
          echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> $GITHUB_ENV

